workflows:
  compose-release:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.georgitasev.scribble"
    scripts:
      - name: Decode keystore
        script: |
          echo "$CM_KEYSTORE" | base64 --decode > keystore.jks
          export CM_KEYSTORE_PATH=$PWD/keystore.jks
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build release APK/AAB
        script: |
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file=codemagic.keystore \
            -Pandroid.injected.signing.store.password=$CM_KEY_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab