workflows:
  sample-workflow:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.georgitasev.scribble"
    artifacts:
          - app/build/outputs/**/*.apk
          - app/build/outputs/**/*.aab