workflows:
  android-workflow:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.GeorgiTasev.Scribble"
        CI: "true"
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Decode keystore
        script: echo "$CM_KEYSTORE" | base64 --decode > codemagic.keystore

      - name: Build Android release
        script: |
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: Debug signing variables
        script: |
          echo "CI: $CI"
          echo "CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD"
          echo "CM_KEY_ALIAS: $CM_KEY_ALIAS"
          echo "CM_KEY_PASSWORD: $CM_KEY_PASSWORD"

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
