workflows:
  compose-release:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.georgitasev.scribble"
    scripts:
      - name: Decode keystore
        script: |
          echo "$CM_KEYSTORE" | base64 --decode > codemagic.keystore
          export CM_KEYSTORE_PATH=$PWD/codemagic.keystore
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build release APK/AAB
        script: ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab