workflows:
  android-workflow:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.GeorgiTasev.Scribble"
        CI: "true"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
