workflows:
  android-compose:
    name: Android Compose Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        CI: true
        KEYSTORE_BASE64: $KEYSTORE_BASE64
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
    scripts:
      - name: Decode keystore
        script: |
          echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
      - name: Build release APK/AAB
        script: ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab